### ISSUE TITLE
Form inputs: Invalid feed back not displayed for list inputs when server validation

### ISSUE THREAD

**Issue by marc-farre** [yiisoft/yii2-bootstrap5#99]
When using a "list" input type (radio, checkbox, dropdown), if the selected value has an error detected on the server side, the error color is not applied and the invalid feedback is not displayed:

![Image](https://github.com/user-attachments/assets/49352558-9afe-44ba-b86a-3a3c4d1356e9)

Because `is-invalid` class should be here:

![Image](https://github.com/user-attachments/assets/17bde209-3238-4ec9-98a7-e90b0df0eade)

Since we have this CSS code:

![Image](https://github.com/user-attachments/assets/5613fcbb-b73b-49b6-8dda-fdc39a69f060)

![Image](https://github.com/user-attachments/assets/f49b6654-5ca6-49a1-890a-7a5a1ee3b18e)

![Image](https://github.com/user-attachments/assets/0e65a0f5-c2ff-4118-a62c-5203bfab196e)

Alternatively, this CSS code fixes the issue if don't change the location of the `is-invalid` class:

```css
.is-invalid[aria-invalid="true"] .form-check-input {
    &, &:checked {
        border-color: var(--bs-form-invalid-border-color);
    }

    &~.form-check-label {
        color: var(--bs-form-invalid-color);
    }

    &~.invalid-feedback {
        display: block;
    }
}
```
